/**
 * 《渡》 ——你是我藏在教案下的一场大雨
 * Story Script - All chapters adapted from the original work
 */

const STORY_SCRIPT = [
  // ============ 开场序幕 ============
  { type: 'bg', value: 'black' },
  { type: 'narration', text: '全市的论坛每隔一阵子就会炸一次。' },
  { type: 'narration', text: '这次炸得格外彻底。' },
  { type: 'narration', text: '一张照片，被人从某个不知名的小号的社交主页扒图，几经辗转贴到了校园墙。照片没有露脸，只有一截白得发青的小腿，和一只搭在烟灰色校服上的、骨骼分明的手指。窗台上的纸页被风吹起来一角，像一片枯叶落在初雪上。' },
  { type: 'narration', text: '事情从第一条评论开始就失控了。' },
  { type: 'dialogue', speaker: '匿名', text: '"对不起，我走错了。"' },
  { type: 'dialogue', speaker: '匿名', text: '"这真的是我们学校的？救命——"' },
  { type: 'dialogue', speaker: '匿名', text: '"有没有一种可能……是某个男老师？"' },
  { type: 'narration', text: '最后一句话被顶到最高赞，因为有人很快扒出了照片的拍摄地点——是高三教学楼四层的窗台。纸页上的字迹经过辨认，是高二下学期的一篇必读课文。消息传遍教学楼只用了一个课间。' },

  // ============ 第一幕：尘袋 ============
  { type: 'transition', effect: 'fade' },
  { type: 'bg', value: 'classroom' },
  { type: 'narration', text: '第一章 尘袋' },
  { type: 'narration', text: '陆砚不是没有想过自己的失控。' },
  { type: 'narration', text: '他今年二十七岁，师范院校毕业，省重点高中语文教师，年级组最年轻的优秀班主任。他讲话慢条斯理，待人接物温和得体，连教导主任都说："小陆这人，稳当。"' },
  { type: 'narration', text: '但此刻，凌晨十一点半，教师公寓的灯还没有熄。陆砚坐在窗边，手里攥着一段灰蓝色的布料。' },
  { type: 'narration', text: '灰蓝色的面料。系绳上还残留着一点洗衣液的味道，清甜底下压着一种更幽深的气息。是体香。活人的、年轻的、干净的体香。' },
  { type: 'narration', text: '——沈临渡的尘袋。' },
  { type: 'narration', text: '三天前他在操场上捡到的。那天学校组织体检，男生们被要求在更衣室换衣服，人挤人乱成一团。他路过时被奔跑的学生撞了一下，手里的备课本散了一地。等他蹲下身去捡，发现塑料袋、包装纸被扫到塑料筐里，那截布片混在一堆杂物里，被一并扔到了器械室。' },
  { type: 'narration', text: '他没扔。' },
  { type: 'narration', text: '他偷偷拿走了。一个学生的尘袋。' },
  { type: 'narration', text: '此刻它躺在书桌上。灰蓝色在台灯下浮出一种暖昧的光泽。陆砚几乎能想象出它贴在沈临渡身上的样子——那个少年上课总爱趴着，校服领子从后颈滑下去，露出后颈那颗小小的痣。他歪头装睡，其实好多次是在看手机，屏幕的光映在睫毛上，那双眼睛亮得不像话。' },
  { type: 'thought', speaker: '陆砚', text: '陆砚，你疯了。' },
  { type: 'narration', text: '他起身去洗了手。洗了很久。洗到指腹的皮肤发皱了。' },
  { type: 'narration', text: '然后擦干手，回到书桌前，把尘袋折好，放进一个密封袋，锁进抽屉的最深处。' },
  { type: 'narration', text: '——就像他在讲台上的样子。体面、干净、滴水不漏。' },
  { type: 'narration', text: '只有他自己知道那层壳底下压着什么。' },

  // ============ 第二幕：痕疤 ============
  { type: 'transition', effect: 'fade' },
  { type: 'bg', value: 'night' },
  { type: 'narration', text: '第二章 痕疤' },
  { type: 'narration', text: '沈临渡从没想过当学霸。' },
  { type: 'narration', text: '他小时候是那种"别人家的孩子"。作文拿过市里二等奖，语文课本上的课文他背得比谁都快。老师夸这孩子是读书的料。' },
  { type: 'narration', text: '转眼就过了一个人一生中的十六年。' },
  { type: 'narration', text: '母亲再嫁，对方带着一个比沈临渡大三岁的儿子，叫裴海生。继父酗酒，脾气暴躁。喝醉的时候打人，清醒的时候也打。母亲护着他，像一堵墙。后来母亲病了，需要长期吃药，不能再出去打工。家里的电视机被继父卖了换酒钱。' },
  { type: 'dialogue', speaker: '裴海生', text: '"你他妈就是个吃白饭的。"' },
  { type: 'narration', text: '沈临渡没有还嘴。' },
  { type: 'narration', text: '他第一次见到裴海生的时候，裴海生就笑着对继父说："这孩子长得跟个小姑娘似的，挺好看。"那种目光，沈临渡后来在很多场合反复见了很多次。' },
  { type: 'narration', text: '裴海生开始偷看他。先是洗澡时推开没有锁的浴室门。然后是深夜，坐在他床边，用一种看一件有趣的玩具的眼神。后来发展到拿他手机冒充他跟同学聊天，一条一条看完，翻到某个女同学发来的"你今天好好看"，笑得前仰后合。' },
  { type: 'dialogue', speaker: '裴海生', text: '"弟弟，你是不是很会让人夸你？那你也让我夸一句——你穿那个确实好看。"' },
  { type: 'narration', text: '"那个"指的是母亲给他买的一件打折的白色T恤。穿在他身上，因为太瘦，领口会往下滑。' },
  { type: 'narration', text: '裴海生没有动手。他只是看。' },
  { type: 'narration', text: '——没有触碰的侵犯，沈临渡不知道该告谁。' },
  { type: 'narration', text: '后来他开始拍照片。在沈临渡睡觉的时候，换衣服的时候。一开始卖给网上的人，一张照片二十块，好的时候上百。沈临渡只偷看过一次他手机上的那个账号——昵称是一串乱码。照片被裁剪得很安全：不露脸，只露一小截腿，或者锁骨。' },
  { type: 'narration', text: '他发过一张尘袋照。那是趁沈临渡在宿舍洗澡时，从门缝拍的。灰蓝色，穿在一个少年身上。照片传到网上之后，那条动态被转了几百次。' },
  { type: 'narration', text: '沈临渡十六岁，学习成绩掉到了倒数。' },
  { type: 'narration', text: '他知道那些事是错的。但他也已经不在乎了。' },

  // ============ 第三幕：课间 ============
  { type: 'transition', effect: 'fade' },
  { type: 'bg', value: 'classroom' },
  { type: 'char_show', pos: 'right', name: 'pei_yuan' },
  { type: 'narration', text: '第三章 课间' },
  { type: 'narration', text: '高二（7）班的课间，是一场小型的分层实验。' },
  { type: 'dialogue', speaker: '裴苑', text: '"我跟你说，沈临渡那个灰袋子简直绝了。有人截到他上体育课的图，那件尘袋是烟灰色，麻的。你猜多少钱？我查了，八成是Brunello Cucinelli去年秋冬款。"' },
  { type: 'narration', text: '裴苑没有说出口的是——那件尘袋不可能是正品。她比谁都清楚。但不重要。她谈论奢侈品的姿态，不是为了说明自己有钱，而是为了说明别人的廉价。' },
  { type: 'dialogue', speaker: '裴苑', text: '"你管他呢。"' },
  { type: 'narration', text: '同桌还在喋喋不休地八卦，裴苑喝了一口咖啡，没有接话。' },
  { type: 'narration', text: '她的目光越过咖啡杯沿，扫了一眼沈临渡的座位。空的。' },

  // 裴听的视角
  { type: 'char_hide', pos: 'right' },
  { type: 'char_show', pos: 'left', name: 'pei_ting' },
  { type: 'narration', text: '裴听把上周的错题本夹在课本下面，用别针别好，推到沈临渡桌上。她做的很隐蔽，像是某种地下工作。' },
  { type: 'narration', text: '她一开始只是因为不服——那张满分的数学卷子，最后一题的解题思路明明是沈临渡对。老师只讲了一种标准解法，沈临渡用的是另一种，更短，更干净。他只考了十九分。但他提出的问题是对的。' },
  { type: 'narration', text: '裴听偷偷记下了那个解法。然后偷偷给他写了一份详细的解题步骤。夹在错题本里。' },
  { type: 'narration', text: '十九分的卷子下面，藏着满分的思路。' },

  // ============ 第四幕：天台 ============
  { type: 'transition', effect: 'fade' },
  { type: 'bg', value: 'rooftop' },
  { type: 'char_hide', pos: 'left' },
  { type: 'char_show', pos: 'center', name: 'shen' },
  { type: 'narration', text: '第四章 天台' },
  { type: 'narration', text: '沈临渡在天台上吹着冷风抽烟。' },
  { type: 'narration', text: '他其实不喜欢烟味。只是把没着落的情绪放在烟里，一吸一吐——好像"呼"的一声，就都散出去了。他打开手机看了一眼那个社交账号的私信。又关上了。' },
  { type: 'dialogue', speaker: '私信', text: '"能不能再发一张。"' },
  { type: 'dialogue', speaker: '私信', text: '"私聊，多少钱？"' },
  { type: 'dialogue', speaker: '私信', text: '"你上次那张真的好看，有没有更好的。"' },
  { type: 'narration', text: '他面无表情地把手机揣回兜里。' },
  { type: 'narration', text: '母亲的药不能断。继父上个月打牌又输了钱——家里的电视机已经卖了。裴海生不缺钱，但裴海生从不给他钱。' },
  { type: 'dialogue', speaker: '裴海生', text: '"弟弟缺钱？哥一句话的事儿。但你要什么，得跟我开口。"' },
  { type: 'narration', text: '裴海生说这句话的时候，手指搭在他的后颈上。大拇指按住他第一颗颈椎骨的位置，没用力，只是反复摩挲。' },
  { type: 'narration', text: '沈临渡没有甩开。他只是沉默。每一秒都很难熬。' },
  { type: 'narration', text: '天台的门突然"吱呀"响了一声。' },
  { type: 'narration', text: '沈临渡迅速把烟掐灭，用脚踩住——但他发现来的人不是保安。他转过头，整个人顿了一下。' },
  { type: 'char_hide', pos: 'center' },
  { type: 'char_show', pos: 'right', name: 'lu' },
  { type: 'narration', text: '陆砚。' },
  { type: 'dialogue', speaker: '陆砚', text: '"你在这里做什么？"' },
  { type: 'char_hide', pos: 'right' },
  { type: 'char_show', pos: 'center', name: 'shen' },
  { type: 'dialogue', speaker: '沈临渡', text: '"陆老师也来天台？"' },
  { type: 'narration', text: '陆砚的目光在他脚下停了一秒。那一秒钟，沈临渡想起自己藏起来的烟头。' },
  { type: 'char_show', pos: 'right', name: 'lu' },
  { type: 'dialogue', speaker: '陆砚', text: '"上课时间不在教室，按旷课处理。"' },
  { type: 'dialogue', speaker: '沈临渡', text: '"哦。"' },
  { type: 'narration', text: '陆砚转身要走。' },
  { type: 'char_hide', pos: 'right' },
  { type: 'dialogue', speaker: '沈临渡', text: '"陆老师。"' },
  { type: 'narration', text: '他停住。' },
  { type: 'char_show', pos: 'center', name: 'shen' },
  { type: 'dialogue', speaker: '沈临渡', text: '"上次讲《爱莲说》，你说周敦颐写\'出淤泥而不染，濯清涟而不妖\'——是说君子即使处在不干净的环境里，也要保持高洁。可是陆老师，如果一个人，他自己就不干净呢？他还有资格当君子吗？"' },
  { type: 'char_show', pos: 'right', name: 'lu' },
  { type: 'narration', text: '陆砚没回头，沈临渡看不见他的表情。但他的后颈很白，在灰扑扑的天台背景里，干净得有些刺眼。' },
  { type: 'dialogue', speaker: '陆砚', text: '"你自己去课文中找答案。回去上课。"' },
  { type: 'narration', text: '沈临渡的眼睛亮了一瞬。但他没有追问。那些亮光被迅速地、刻意地压了回去。' },
  { type: 'dialogue', speaker: '沈临渡', text: '"陆老师果然是陆老师。就是不知道，你自己信不信你讲的。"' },
  { type: 'narration', text: '他没有踩灭那支烟，经过陆砚身边的时候，肩头几乎擦过陆砚的胳膊。' },
  { type: 'narration', text: '陆砚站在原地，闻到一股混着烟草味的、若有若无的洗衣液的清甜。他的手指不易察觉地蜷了一下。' },

  // ============ 第五幕：夜酒 ============
  { type: 'transition', effect: 'fade' },
  { type: 'bg', value: 'bar' },
  { type: 'char_hide_all' },
  { type: 'char_show', pos: 'left', name: 'song' },
  { type: 'char_show', pos: 'right', name: 'lu' },
  { type: 'narration', text: '第五章 夜酒' },
  { type: 'narration', text: '周六晚上，陆砚被老友宋知远拉去喝酒。' },
  { type: 'narration', text: '宋知远是陆砚大学时期的朋友，现在在北京一家游戏公司做运营。性格张扬而松弛，说话不靠谱的时候居多，但关键时刻能一眼看穿人。' },
  { type: 'dialogue', speaker: '宋知远', text: '"你这脸都成什么样了。失恋了？"' },
  { type: 'dialogue', speaker: '陆砚', text: '"没有。"' },
  { type: 'dialogue', speaker: '宋知远', text: '"装。你还能瞒得过我？上回见你这样，还是你考研失败那回——不对，比那回还难看。谁啊？同事？被主任欺压了？给你穿小鞋了？"' },
  { type: 'dialogue', speaker: '陆砚', text: '"没有。"' },
  { type: 'dialogue', speaker: '宋知远', text: '"那是谁啊？"' },
  { type: 'dialogue', speaker: '陆砚', text: '"我说了没有。"' },
  { type: 'narration', text: '宋知远哼了一声，继续喝酒。' },
  { type: 'narration', text: '两个人喝了很多。' },
  { type: 'dialogue', speaker: '陆砚', text: '"知远。"' },
  { type: 'dialogue', speaker: '宋知远', text: '"嗯？"' },
  { type: 'dialogue', speaker: '陆砚', text: '"你记不记得，我们以前聊过——如果一个人明知道自己不该做什么事，但他停不下来。那算什么？"' },
  { type: 'dialogue', speaker: '宋知远', text: '"赌博？"' },
  { type: 'dialogue', speaker: '陆砚', text: '"不赌博。"' },
  { type: 'dialogue', speaker: '宋知远', text: '"吸毒？"' },
  { type: 'dialogue', speaker: '陆砚', text: '"不是。"' },
  { type: 'narration', text: '宋知远把筷子往桌上一搁，身子往后一靠。' },
  { type: 'dialogue', speaker: '宋知远', text: '"那就是赌命。赌命没药医。要么你自己把自己劝住，要么你被那个东西吃干净。"' },
  { type: 'narration', text: '陆砚沉默了很久。' },
  { type: 'dialogue', speaker: '陆砚', text: '"你挺会说话的。"' },
  { type: 'dialogue', speaker: '宋知远', text: '"那当然。我好歹也是论坛历年精选评论榜前三。别人大学四年没白给我补课。"' },
  { type: 'narration', text: '陆砚低头看着酒杯。灯光下，琥珀色的液体里有细小的漩涡。' },
  { type: 'narration', text: '他脑海里不受控制地浮现出一个画面——灰蓝色的尘袋。' },

  // ============ 第六幕：笔记 ============
  { type: 'transition', effect: 'fade' },
  { type: 'bg', value: 'classroom' },
  { type: 'char_hide_all' },
  { type: 'char_show', pos: 'center', name: 'shen' },
  { type: 'narration', text: '第六章 笔记' },
  { type: 'narration', text: '又一个晚自习。沈临渡踩着铃声进了教室。' },
  { type: 'narration', text: '自从论坛那件事之后，沈临渡走到哪儿都能感受到目光——探究的、猎奇的、兴奋的、不怀好意的。他已经习惯了。或者说，他早就习惯了。从很多年前开始。' },
  { type: 'narration', text: '他在座位上坐下来，习惯性地伸手去掏抽屉里的东西。然后手指停了一下。' },
  { type: 'narration', text: '是一本笔记本。普通的牛皮纸封面，没有署名。翻开第一页，是工工整整的数学笔记——《解析几何·椭圆》，每一页都满满当当：公式推导、例题、用红笔标注的知识点。' },
  { type: 'narration', text: '翻到最后一页。留白处，一行很小的字，工整到有些犹豫，像是下了很大决心才写上去的：' },
  { type: 'dialogue', speaker: '笔记上的字', text: '"下一次月考，一定要考及格。加油。"' },
  { type: 'narration', text: '没有署名。' },
  { type: 'narration', text: '沈临渡把笔记本合上，抬头扫了一圈。他看了几个人，最后目光落在裴听的背影上。她低着头在背英语单词。耳根有一点红。' },
  { type: 'narration', text: '他认识那个笔记本。裴听每节课都在记。她成绩是年级前五。' },

  // ============ 第七幕：课堂 ============
  { type: 'transition', effect: 'fade' },
  { type: 'bg', value: 'classroom' },
  { type: 'char_hide_all' },
  { type: 'char_show', pos: 'right', name: 'lu' },
  { type: 'char_show', pos: 'left', name: 'shen' },
  { type: 'narration', text: '第七章 课堂' },
  { type: 'narration', text: '上午第三节课，语文。' },

  { type: 'narration', text: '陆砚拿着教案走进教室时，教室里安静了一瞬。他的课在年级里口碑一致好评——讲得清楚，人又温和。后排有几个女生在笔记本上偷偷画画，陆砚只当没看见。' },
  { type: 'dialogue', speaker: '陆砚', text: '"今天我们讲《归去来兮辞》。这篇文章写于陶渊明辞官归隐的那一年，为什么要写\'归去来兮，田园将芜胡不归\'？你把这一句和陶渊明所处的时代背景放在一起看，就能明白他在挣扎什么。"' },
  { type: 'narration', text: '他的目光扫过全班。在后排停了不到一秒。然后移开了。' },
  { type: 'narration', text: '沈临渡坐在最后一排，没有趴着。他的眼睛在教室的日光灯下显得格外透亮，像某种浅水里的玻璃珠子——看着清澈，实际上深不见底。' },

  { type: 'dialogue', speaker: '陆砚', text: '"陶渊明归隐的时候，写了五个字——田园将芜胡不归。这不矛盾。人在最痛苦的时候，反而最清楚什么是自己真正想要的东西。"' },
  { type: 'char_show', pos: 'center', name: 'shen' },
  { type: 'dialogue', speaker: '沈临渡', text: '"陆老师。"' },
  { type: 'narration', text: '全班转头。' },
  { type: 'dialogue', speaker: '沈临渡', text: '"陶渊明回家的时候，他种的地真的还有救吗？"我查过，他回去第二年就遭了旱灾，饿得去邻居家讨米。他写那些句子的时候——到底是真的安心了，还是只是假装想通了？"' },
  { type: 'narration', text: '教室里安静了。' },
  { type: 'dialogue', speaker: '陆砚', text: '"痛不痛只有自己知道。他选择写出来。写出来，就是他的渡。"' },
  { type: 'narration', text: '他顿了一下。好像在斟酌用词。' },
  { type: 'dialogue', speaker: '陆砚', text: '"渡，就是他在试着让自己过去。"' },
  { type: 'narration', text: '沈临渡看了他很久。然后忽然笑了，是那种没力气、没撑住的笑。' },
  { type: 'dialogue', speaker: '沈临渡', text: '"哦。渡这个字挺好听的。"' },
  { type: 'narration', text: '陆砚不确定他听懂了没有。但他感到自己的心脏被什么敲了一下。' },
  { type: 'narration', text: '他低下头翻了一页教案。教案留白处，他自己都没有意识到——笔尖无意识地画了一个对勾。墨水的颜色，像一片叶子。灰蓝色的。' },

  // ============ 第八章：揭穿 ============
  { type: 'transition', effect: 'fade' },
  { type: 'bg', value: 'campus' },
  { type: 'char_hide_all' },
  { type: 'char_show', pos: 'center', name: 'shen' },
  { type: 'rain_start' },
  { type: 'narration', text: '第八章 揭穿' },
  { type: 'narration', text: '风暴是毫无征兆地落下来的。' },
  { type: 'narration', text: '不知道是谁，把沈临渡那个私信账号的截图发到了学校大群——尘袋照、后台聊天记录、发帖时间线，还有一段添油加醋的文字：' },
  { type: 'dialogue', speaker: '匿名', text: '"穿尘袋勾引人的弟弟，谁看了不说一句好看？"' },
  { type: 'narration', text: '截图被打印出来。钉在公告栏上。传遍全校。' },
  { type: 'narration', text: '沈临渡是最后一个知道的。' },
  { type: 'narration', text: '他从天台下来，走过楼道拐角的时候，看到一群人在笑。他走近了，人群自动让开一条路。公告栏上的纸已经被撕烂了几张。他的照片在上面，脸上踩了一个脚印。' },
  { type: 'narration', text: '沈临渡看着那几张纸，面无表情。' },
  { type: 'dialogue', speaker: '同学A', text: '"沈临渡，你妈是不是也很会穿啊？"' },
  { type: 'dialogue', speaker: '同学B', text: '"有的是尘袋，有的什么都没有……你说变态不？"' },
  { type: 'dialogue', speaker: '同学C', text: '"不是，他长成这样……哪个男的看了不迷糊？"' },
  { type: 'narration', text: '沈临渡把那几张纸扯下来，揉成一团。然后他直起身，平静地看了一圈周围的人。' },
  { type: 'dialogue', speaker: '沈临渡', text: '"说完了？再说下去，我怕你们晚上做噩梦。"' },
  { type: 'narration', text: '他的表情——他太熟悉该怎么摆出这种表情了。不是愤怒，不是委屈，不是恐惧。是一种更深更冷的东西：无所谓。一种已经被磨了太多遍的、刀子一样薄的、触目惊心的无所谓。' },
  { type: 'narration', text: '然后他从人群中走出去。没有回头看。' },

  // ============ 第九章：深夜 ============
  { type: 'transition', effect: 'fade' },
  { type: 'bg', value: 'riverbank' },
  { type: 'narration', text: '第九章 深夜' },
  { type: 'narration', text: '沈临渡那天晚上没有回宿舍。' },
  { type: 'narration', text: '学校后门外有一条河。十月的夜风冷得像刀子。他坐在河堤的台阶上，膝盖抵着下巴，把自己团成很小的一团。手机里是裴海生发来的消息。' },
  { type: 'dialogue', speaker: '裴海生', text: '"弟弟，听说你们学校炸开锅了。那些照片我看了，拍得确实不错。你跟我说实话，发那些照片的时候，你有没有自己也觉得挺享受的？要不再多拍几张……"' },
  { type: 'dialogue', speaker: '沈临渡', text: '"滚。"' },
  { type: 'narration', text: '他没有哭。他只是觉得冷。' },
  { type: 'narration', text: '然后他想到了母亲。母亲靠药物维持，一种药一个月四百块。医生说不能断。继父不管。裴海生更不会管。他十五岁开始偷着在网上卖东西——不是什么光彩的行当。他没有别的办法。' },
  { type: 'narration', text: '他只想渡过去。' },
  { type: 'narration', text: '他几乎想放弃了。不是那种歇斯底里、从天台上往下跳的那种放弃。是另一种：温水煮青蛙式的。站太久太累了，就坐一会儿。坐下去，就不想起来了。' },
  { type: 'narration', text: '然后他听到了脚步声。' },
  { type: 'narration', text: '不是学生的脚步。学生不会在这种时候、这种地方。皮鞋踩在石板路上，不疾不徐，像走了很久，又像在犹豫要不要走过来。' },
  { type: 'narration', text: '沈临渡抬起头。' },
  { type: 'char_hide', pos: 'center' },
  { type: 'char_show', pos: 'right', name: 'lu' },
  { type: 'dialogue', speaker: '沈临渡', text: '"陆老师？你怎么会在这里？"' },
  { type: 'dialogue', speaker: '陆砚', text: '"我住在教师公寓。散步。"' },
  { type: 'dialogue', speaker: '沈临渡', text: '"大半夜散步，散到河堤？"' },
  { type: 'dialogue', speaker: '陆砚', text: '"嗯。"' },
  { type: 'dialogue', speaker: '沈临渡', text: '"你就不怕学生说你闲话？"' },
  { type: 'dialogue', speaker: '陆砚', text: '"这里没有学生。只有你。"' },
  { type: 'narration', text: '沈临渡愣了一瞬，然后忽然笑了。不是那种皮笑肉不笑——是真的被逗笑了。' },
  { type: 'dialogue', speaker: '沈临渡', text: '"陆老师，你挺有胆的。"' },
  { type: 'narration', text: '陆砚没有说话。他看着对岸的灯火，像在看一道很远的风景。' },
  { type: 'narration', text: '沉默持续了很长时间。然后陆砚从外套口袋里掏出一盒牛奶，搁在两人之间的台阶上。草莓味的。温的。' },
  { type: 'dialogue', speaker: '沈临渡', text: '"这算什么？"' },
  { type: 'dialogue', speaker: '陆砚', text: '"你没吃晚饭。"' },
  { type: 'dialogue', speaker: '沈临渡', text: '"你怎么知道？"' },
  { type: 'dialogue', speaker: '陆砚', text: '"食堂阿姨跟我抱怨，说你今天晚餐又没去。"' },
  { type: 'narration', text: '沈临渡沉默了一会儿。然后他拿过那盒牛奶，插上吸管，喝了一口。' },
  { type: 'dialogue', speaker: '陆砚', text: '"论坛的事，我已经跟年级组说了。你不必跟任何人解释。"' },
  { type: 'dialogue', speaker: '沈临渡', text: '"哦。"' },
  { type: 'dialogue', speaker: '陆砚', text: '"如果你需要帮助——可以找我。"' },
  { type: 'narration', text: '沈临渡偏头看他。路灯太暗，但那双眼睛里有一点温度，像冬天教室里的暖气片——不烫，恰好能暖手。' },
  { type: 'char_show', pos: 'center', name: 'shen' },
  { type: 'dialogue', speaker: '沈临渡', text: '"陆老师。你是不是对每个学生都这么好？"' },
  { type: 'narration', text: '陆砚没有立刻回答。' },
  { type: 'dialogue', speaker: '陆砚', text: '"不是。"' },
  { type: 'narration', text: '他的声音很轻。' },
  { type: 'narration', text: '沈临渡愣了一瞬。' },
  { type: 'rain_stop' },
  { type: 'dialogue', speaker: '陆砚', text: '"十一点之前回宿舍，明天还有早读。"' },
  { type: 'narration', text: '他起身走了。皮鞋踩在石板路上的声音越来越远。' },
  { type: 'narration', text: '沈临渡坐在原地，握着那盒温热的草莓牛奶，掌心被捂得很烫。' },

  // ============ 第十章：失控 ============
  { type: 'transition', effect: 'fade' },
  { type: 'bg', value: 'night' },
  { type: 'char_hide_all' },
  { type: 'narration', text: '第十章 失控' },
  { type: 'narration', text: '陆砚回到公寓，在黑暗里坐了二十分钟。' },
  { type: 'narration', text: '他跟自己承认。他去找沈临渡，不是因为散步。' },
  { type: 'narration', text: '他看到晚自习后沈临渡没有回宿舍。他等了三十分钟，忍不住了。他跟自己说这是"关注学生安全"。他知道自己撒谎。' },
  { type: 'narration', text: '一切都不对劲。一个老师担心学生，不应该深夜一个人跑去河堤。他应该是打电话给班主任，通知家长，联系心理干预——他有无数条"正确"的路可以走。但他选了那条唯一不对的路。' },
  { type: 'narration', text: '他在河堤上看到沈临渡缩成一团的时候，心脏停了一拍。那一瞬间他什么都没想，只想走过去。走得很近。近到能看清少年冻得发青的指尖。' },
  { type: 'narration', text: '他说"不是"的时候，心跳声盖过了河水的声音。' },
  { type: 'narration', text: '这不是喜欢。' },
  { type: 'narration', text: '——这是自毁。' },
  { type: 'narration', text: '陆砚在黑暗中反复咀嚼宋知远的话：' },
  { type: 'dialogue', speaker: '宋知远', text: '"要么你自己把自己劝住，要么你被那个东西吃干净。"' },
  { type: 'narration', text: '他闭上眼睛。然后翻了个身。他知道——自己已经快被吃干净了。' },

  // ============ 第十一章：缝隙 ============
  { type: 'transition', effect: 'fade' },
  { type: 'bg', value: 'classroom' },
  { type: 'char_show', pos: 'left', name: 'pei_ting' },
  { type: 'narration', text: '第十一章 缝隙' },
  { type: 'narration', text: '日子在往前走。' },
  { type: 'narration', text: '论坛风波之后，学校没追查。教导主任找沈临渡谈过一次话。沈临渡什么也没解释。一个硬币扔进水里，涟漪散尽，水面恢复了沉寂。' },
  { type: 'narration', text: '裴听开始频繁地出现在沈临渡的视野里。' },
  { type: 'narration', text: '她每次的动作都很快——把东西放下就走。有时候是一本笔记，有时候是一盒牛奶或一个苹果，有时候只是站在他座位旁边愣了一下，然后走开。' },
  { type: 'narration', text: '沈临渡觉得好笑。但他把那盒牛奶喝了。红豆味的。甜的。' },
  { type: 'narration', text: '他把喝空的牛奶盒放在桌上，轻轻敲了一下——那层锡箔纸发出清脆的响声。' },
  { type: 'narration', text: '其实他知道有一种东西很久没有动过了。裴听碰了它的边缘。' },

  // ============ 第十二章：援手 ============
  { type: 'transition', effect: 'fade' },
  { type: 'bg', value: 'campus' },
  { type: 'char_hide_all' },
  { type: 'char_show', pos: 'left', name: 'pei_yuan' },
  { type: 'char_show', pos: 'right', name: 'shen' },
  { type: 'narration', text: '第十二章 援手' },
  { type: 'narration', text: '裴苑是在体育课自由活动的时候主动走向沈临渡的。' },
  { type: 'dialogue', speaker: '裴苑', text: '"沈临渡同学？没找错人吧。"' },
  { type: 'dialogue', speaker: '沈临渡', text: '"没找错。裴大小姐，有什么话你说吧。"' },
  { type: 'dialogue', speaker: '裴苑', text: '"首先，照片的事，不是我干的。其次，传播的人我大致知道是谁。我不认可这种做法，也不准备追究——因为追究没有意义。"' },
  { type: 'dialogue', speaker: '沈临渡', text: '"挺好。"' },
  { type: 'narration', text: '裴苑沉默了一瞬。沈临渡在笑，那种笑她觉得太不像一个十七岁的人应该有的表情。' },
  { type: 'dialogue', speaker: '沈临渡', text: '"找我到底什么事？如果是道歉就不必了——那些照片和流言，放久了就会消失的。"' },
  { type: 'dialogue', speaker: '裴苑', text: '"不能。"' },
  { type: 'dialogue', speaker: '沈临渡', text: '"那不就结了。"' },
  { type: 'dialogue', speaker: '裴苑', text: '"但我可以做另一件事。"' },
  { type: 'narration', text: '她从口袋里掏出一张名片。放在两人之间的座位上。' },
  { type: 'dialogue', speaker: '裴苑', text: '"我家的法律顾问。那些截图涉及未成年人隐私泄露，发布者和传播者都涉嫌违法。我不以个人名义——以证据链的名义。如果你需要，他会帮你。不需要任何费用。"' },
  { type: 'narration', text: '沈临渡看着那张名片，没有拿。他沉默了很久。' },
  { type: 'dialogue', speaker: '沈临渡', text: '"你为什么要帮我？"' },
  { type: 'dialogue', speaker: '裴苑', text: '"因为我觉得那件事不公平。我不喜欢不公平的事。"' },
  { type: 'narration', text: '她站起来拍了拍裙子上的灰，走了。' },
  { type: 'narration', text: '沈临渡把名片捡起来。然后揣进了校服口袋里。' },

  // ============ 第十三章：好看 ============
  { type: 'transition', effect: 'fade' },
  { type: 'bg', value: 'schoolgate' },
  { type: 'char_hide_all' },
  { type: 'char_show', pos: 'center', name: 'shen' },
  { type: 'char_show', pos: 'right', name: 'peihaisheng' },
  { type: 'narration', text: '第十三章 好看' },
  { type: 'narration', text: '十月底，期中考试。沈临渡考了年级第二十三名。上次是倒数第九。' },
  { type: 'narration', text: '十一月初的一天傍晚，沈临渡出校门时看到了裴海生。' },
  { type: 'dialogue', speaker: '裴海生', text: '"弟弟，放学了？"' },
  { type: 'narration', text: '沈临渡的脚步顿了一秒，然后继续走。' },
  { type: 'narration', text: '裴海生伸出手臂搭住他的肩。他比沈临渡高半个头，手指扣在肩上像一把钳子。大拇指习惯性地按在他的后颈上。' },
  { type: 'dialogue', speaker: '裴海生', text: '"怎么？觉得哥不够意思了？"' },
  { type: 'dialogue', speaker: '沈临渡', text: '"你来做什么？"' },
  { type: 'dialogue', speaker: '裴海生', text: '"看你啊。妈说你最近不怎么回家了，我来关心关心你。"' },
  { type: 'narration', text: '沈临渡知道那是假的。母亲不会托裴海生带话。裴海生查他行踪另有目的。' },
  { type: 'dialogue', speaker: '裴海生', text: '"对了，那个药——你妈吃的那种——医院太贵了。我有个朋友路子广，能弄到同一种药，价格便宜很多。要不要？"' },
  { type: 'dialogue', speaker: '沈临渡', text: '"什么路子？"' },
  { type: 'dialogue', speaker: '裴海生', text: '"仿制药。印度那边过来的。医院开八百的，他两百搞定。"' },
  { type: 'dialogue', speaker: '沈临渡', text: '"不要。"' },
  { type: 'dialogue', speaker: '裴海生', text: '"弟弟——"' },
  { type: 'dialogue', speaker: '沈临渡', text: '"我说不要。"' },
  { type: 'narration', text: '他甩开裴海生的手。动作很硬。裴海生的笑容凝固了一瞬，又若无其事地摊了摊手。' },
  { type: 'dialogue', speaker: '裴海生', text: '"行，你说不要就不要。弟弟，但你想清楚——你在学校待不了多久了。全学校都知道你的事了，你还想怎么待？你要给自己找个后路。这后路，只有你哥能给你。"' },
  { type: 'narration', text: '他转身走了。' },
  { type: 'narration', text: '陆砚刚好从教学楼里出来。他站在二楼走廊的窗边，远远看到了校门口那一幕。太远，听不见他们在说什么。但他看到了裴海生搭在沈临渡肩上的手，以及沈临渡甩开那只手时的动作——不是普通的躲闪。是恐惧的。是憎恶的。像一只被踩了尾巴的猫。' },

  // ============ 第十四章：坦白 ============
  { type: 'transition', effect: 'fade' },
  { type: 'bg', value: 'classroom' },
  { type: 'char_hide_all' },
  { type: 'char_show', pos: 'right', name: 'lu' },
  { type: 'char_show', pos: 'left', name: 'shen' },
  { type: 'narration', text: '第十四章 坦白' },
  { type: 'narration', text: '陆砚找了个理由把沈临渡留下来。理由是"作文需要单独辅导"。' },
  { type: 'narration', text: '放学后的教室空荡荡的。夕阳从窗户斜进来，在课桌上铺了一层赭红色的光。' },
  { type: 'dialogue', speaker: '陆砚', text: '"你先看看你的作文，结构上的问题……结尾收得太快了。"' },
  { type: 'dialogue', speaker: '沈临渡', text: '"陆老师。你不是真为了给我讲作文吧。"' },
  { type: 'dialogue', speaker: '沈临渡', text: '"校门口那个人——是你什么人？"' },
  { type: 'dialogue', speaker: '沈临渡', text: '"我继兄。裴海生。"' },
  { type: 'dialogue', speaker: '陆砚', text: '"他对你做了什么？"' },
  { type: 'narration', text: '沈临渡笑了。' },
  { type: 'dialogue', speaker: '沈临渡', text: '"陆老师，你管太多了。"' },
  { type: 'dialogue', speaker: '陆砚', text: '"我不管。我在问你。"' },
  { type: 'dialogue', speaker: '沈临渡', text: '"你这是逼我。"' },
  { type: 'dialogue', speaker: '陆砚', text: '"你不说，我也知道——他碰你的时候，你害怕。"' },
  { type: 'narration', text: '沉默。很长的沉默。' },
  { type: 'dialogue', speaker: '沈临渡', text: '"他没有碰我。没有做那种事。他只是……看。趁我洗澡的时候看。趁我睡着的时候看。拍照片。然后卖。"' },
  { type: 'narration', text: '他说得很慢。像一条很深的河，水很冷。' },
  { type: 'dialogue', speaker: '沈临渡', text: '"他从来不动手。他只是让我知道他在看。让我知道——我活在他的注视之下。无处可逃。"' },
  { type: 'narration', text: '陆砚的手在桌子底下攥成了拳头。指节发白。' },
  { type: 'dialogue', speaker: '陆砚', text: '"什么时候的事？"' },
  { type: 'dialogue', speaker: '沈临渡', text: '"上个月。我回家拿换季衣服。他进来的时候我没醒。后来——我发现他拍了照片。他笑，说发朋友圈用的。不会有人知道。"' },
  { type: 'dialogue', speaker: '陆砚', text: '"你妈知道吗？"' },
  { type: 'dialogue', speaker: '沈临渡', text: '"她每天晚上吃药。睡到第二天中午。她连自己吃饭都记不住。"' },
  { type: 'narration', text: '陆砚沉默了很久。久到沈临渡以为这个老师终于打算放弃了。' },
  { type: 'dialogue', speaker: '陆砚', text: '"你不应该是那个扛下一切的人。你还是个孩子。"' },
  { type: 'narration', text: '沈临渡愣住了。' },
  { type: 'narration', text: '他的眼眶红了一瞬。很快。快到像是错觉。' },
  { type: 'dialogue', speaker: '沈临渡', text: '"陆老师，你别再说这种话了。"' },
  { type: 'dialogue', speaker: '陆砚', text: '"为什么？"' },
  { type: 'dialogue', speaker: '沈临渡', text: '"因为你说这种话，我会当真。"' },

  // ============ 第十五章：双轨 ============
  { type: 'transition', effect: 'fade' },
  { type: 'bg', value: 'classroom' },
  { type: 'char_hide_all' },
  { type: 'narration', text: '第十五章 双轨' },
  { type: 'narration', text: '十一月下旬开始，一些微妙的变化在不知不觉中发生了。' },
  { type: 'narration', text: '沈临渡开始上课了。每节课都来，很少再趴着睡觉。他换了一件洗得发白的旧T恤，但那件T恤很干净。' },
  { type: 'narration', text: '裴听的笔记也变了形式——她开始在他的笔记本上留自己的解题思路。那些思路有时候比他的还要好。沈临渡给她加注，用铅笔在空白处写个"谢了"，字越来越不潦草。' },
  { type: 'narration', text: '裴苑跟同寝室的女生闹掰了，没人敢说一个字。只有人私下议论说，她去找过校长，为的是举报那些传播沈临渡照片的学生。校长没处理。她的法律顾问最后还是被启动了。' },
  { type: 'narration', text: '十二月，全市联考。沈临渡数学考了一百三十七分。年级排名从倒数直接杀进前一百。' },
  { type: 'narration', text: '数学老师在办公室看到成绩单，看了好几遍，怀疑是作弊。陆砚说不用查，不是作弊。' },
  { type: 'narration', text: '因为沈临渡的数学卷子他看了——那些解题过程不可能是抄的。路子太野，太干净。' },

  // ============ 第十六章：坠落 ============
  { type: 'transition', effect: 'fade' },
  { type: 'bg', value: 'office' },
  { type: 'char_show', pos: 'center', name: 'lu' },
  { type: 'narration', text: '第十六章 坠落' },
  { type: 'narration', text: '陆砚的语文成绩单也出来了。沈临渡语文考了九十八分。作文分数不高，但阅读题几乎全对。' },
  { type: 'narration', text: '他看了沈临渡的作文。题目是《我的世界》。沈临渡写的是：' },
  { type: 'dialogue', speaker: '沈临渡的作文', text: '"我家很小，像一个纸盒子。纸盒子上破了一个洞，雨漏进来的时候，我拿胶带粘上。后来又破了。后来我学会不去粘它了——就让雨漏进来。我没有见过什么名山大川。课本上说的黄河长江，我没去过。老师说的大唐盛世我没有见过。我去过最远的地方是市里的医院。我妈妈在那里。我的世界不好。但我喜欢它。它是这个世界上唯一属于我的东西。有一天我会离开这里，去很远的地方。"' },
  { type: 'narration', text: '陆砚反复看了很多遍。最后在作文末尾写了几个字。写了又划掉，改了又改。只留下一句——' },
  { type: 'dialogue', speaker: '陆砚的批注', text: '"这个世界不止一种颜色。加油。"' },
  { type: 'narration', text: '他用红笔把"加油"圈起来。但红墨水透过去了。那个被划掉的字，仔细看的话，还看得见。' },
  { type: 'narration', text: '是一个"我"字。' },

  // ============ 第十七章：渡 ============
  { type: 'transition', effect: 'fade' },
  { type: 'bg', value: 'bar' },
  { type: 'char_hide_all' },
  { type: 'char_show', pos: 'left', name: 'song' },
  { type: 'char_show', pos: 'right', name: 'lu' },
  { type: 'narration', text: '第十七章 渡' },
  { type: 'narration', text: '十二月的最后一个周末，宋知远约陆砚吃饭。' },
  { type: 'dialogue', speaker: '宋知远', text: '"上次说的那个，有下文没有？"' },
  { type: 'narration', text: '陆砚没有点头也没有摇头。他的沉默就是回答。' },
  { type: 'dialogue', speaker: '宋知远', text: '"你碰过他没有？"' },
  { type: 'dialogue', speaker: '陆砚', text: '"没有。"' },
  { type: 'dialogue', speaker: '宋知远', text: '"想过没有？"' },
  { type: 'narration', text: '陆砚没说话。' },
  { type: 'dialogue', speaker: '宋知远', text: '"陆砚——你跟我说实话。你到底碰过他没有？一根手指头都算。"' },
  { type: 'dialogue', speaker: '陆砚', text: '"没有。什么都没有。"' },
  { type: 'narration', text: '他抬起眼睛。那双眼睛不是悲伤。是一种极度压抑之后的淤血。' },
  { type: 'dialogue', speaker: '陆砚', text: '"但我每天想。控制不住地想。我把自己关在公寓里——我批作业的时候想。我明明在看他的字，但他写的每一个字——我都在想他写那些字的手指。我想他的声音。我想他叫我\'陆老师\'的时候，嘴唇是怎么动的。我疯了。我彻底疯了。"' },
  { type: 'narration', text: '宋知远沉默了很久。' },
  { type: 'dialogue', speaker: '宋知远', text: '"你知道这意味着什么吗？"' },
  { type: 'dialogue', speaker: '陆砚', text: '"我知道。"' },
  { type: 'dialogue', speaker: '宋知远', text: '"你是老师。他是学生。他未成年。"' },
  { type: 'dialogue', speaker: '陆砚', text: '"我知道。"' },
  { type: 'dialogue', speaker: '宋知远', text: '"你的未来、你的工作、你的整个人生——都会毁掉。你明白吗？"' },
  { type: 'dialogue', speaker: '陆砚', text: '"我明白。"' },
  { type: 'narration', text: '陆砚低下头。手指插进头发里。' },
  { type: 'narration', text: '宋知远看着他，看了很久。然后他把酒杯往陆砚面前推了推。' },
  { type: 'dialogue', speaker: '宋知远', text: '"那还有救。你还知道让自己别过去——说明你还站在悬崖的这边。"' },
  { type: 'dialogue', speaker: '宋知远', text: '"我教你一件事——把你偷的东西还回去。还给那个孩子。还给他光。"' },

  // ============ 第十八章：寒衣 ============
  { type: 'transition', effect: 'fade' },
  { type: 'bg', value: 'classroom' },
  { type: 'char_hide_all' },
  { type: 'narration', text: '第十八章 寒衣' },
  { type: 'narration', text: '那天晚上，陆砚把那截灰蓝色的尘袋从抽屉里拿了出来。在手里攥了很久。然后他走进卫生间，打开水龙头，看着那张布片被冲得湿透了。最后用一个密封袋装好，扎紧口。扔进了垃圾桶。' },
  { type: 'narration', text: '他没有扔掉自己。但他把那个让他失控的东西扔掉了。' },
  { type: 'narration', text: '一月初，天越来越冷了。沈临渡穿得很薄——只有一件长袖T恤和校服外套。唯一的一件旧毛衣起球了，袖子磨得发白。' },
  { type: 'narration', text: '后勤处多了一件全新的冬季校服。登记表上写着是"学校资助贫困生"。沈临渡收到这件校服的时候，在口袋里摸到一张折得很小的纸条。纸条上没有字。只有一朵铅笔画的对勾。蓝色的。' },
  { type: 'narration', text: '沈临渡拿着那张纸条看了很久。然后他把纸条折好，放进校服内袋里——跟那张裴苑给的名片放在一起。' },
  { type: 'narration', text: '他在陆砚的课上，认真地举了一次手。' },
  { type: 'dialogue', speaker: '沈临渡', text: '"陆老师。你讲完杜甫的《茅屋为秋风所破歌》了吗？杜甫说\'安得广厦千万间，大庇天下寒士俱欢颜\'。可是他自己住在破房子里，还操心别人住不住得起房子——这算不算蠢？"' },
  { type: 'dialogue', speaker: '陆砚', text: '"算蠢。但那种蠢，是以为自己是灯，想去照亮别人——最后也照亮了自己。"' },
  { type: 'narration', text: '沈临渡低下头。翻开作文本。那一页上，没有写作文。只写了一行小字：' },
  { type: 'dialogue', speaker: '沈临渡', text: '"我想考上大学。去很远的地方。"' },

  // ============ 第十九章：谏 ============
  { type: 'transition', effect: 'fade' },
  { type: 'bg', value: 'office' },
  { type: 'char_hide_all' },
  { type: 'char_show', pos: 'center', name: 'lu' },
  { type: 'narration', text: '第十九章 谏' },
  { type: 'narration', text: '寒假前最后一周，陆砚去了一趟校长办公室。' },
  { type: 'narration', text: '他提交了一份调动申请——下学期不再担任高二（7）班的语文课教学。理由是"教学任务调整请求，希望能带新一届高一"。' },
  { type: 'narration', text: '校长同意了。' },
  { type: 'narration', text: '陆砚走出校长办公室的时候，在走廊上长长地吁了一口气。' },
  { type: 'narration', text: '这是他给自己的判罚。远离。把距离拉长到他的控制力范围之外。' },
  { type: 'narration', text: '他必须让沈临渡去活他自己的命。' },

  // ============ 第二十章：最后一课 ============
  { type: 'transition', effect: 'fade' },
  { type: 'bg', value: 'classroom' },
  { type: 'char_show', pos: 'right', name: 'lu' },
  { type: 'char_show', pos: 'left', name: 'shen' },
  { type: 'narration', text: '第二十章 最后一课' },
  { type: 'narration', text: '学期最后一节语文课。陆砚做了一个学期的知识梳理，从《诗经》讲到近现代散文。下课前五分钟，他放下粉笔。' },
  { type: 'dialogue', speaker: '陆砚', text: '"这学期的课就到这里。下学期——会有一位新老师来接我的课。希望你们继续努力。"' },
  { type: 'narration', text: '教室里安静了一瞬。然后炸开了。' },
  { type: 'dialogue', speaker: '前排女生', text: '"陆老师你要调走？"' },
  { type: 'dialogue', speaker: '陆砚', text: '"是教学安排上的调整。新老师也很优秀。"' },

  // ============ CHOICE POINT 1 ============
  { type: 'choice', choices: [
    { text: '（沈临渡）站起来追问原因', jump: 'shen_stands_up', flag: 'choice_last_class', value: 'stand' },
    { text: '（沈临渡）沉默地坐在原位', jump: 'shen_stays_silent', flag: 'choice_last_class', value: 'silent' }
  ] },

  // Branch A: stands up
  { type: 'label', name: 'shen_stands_up' },
  { type: 'dialogue', speaker: '沈临渡', text: '"陆老师。为什么？"' },
  { type: 'narration', text: '他站了起来。教室里的所有声音都消失了。' },
  { type: 'dialogue', speaker: '陆砚', text: '"这是学校的安排。"' },
  { type: 'dialogue', speaker: '沈临渡', text: '"你安排的对不对？"' },
  { type: 'narration', text: '陆砚沉默了。' },
  { type: 'dialogue', speaker: '沈临渡', text: '"你不敢看我。"' },
  { type: 'narration', text: '下课铃响了。陆砚拿起教案，没有回头。' },
  { type: 'dialogue', speaker: '沈临渡', text: '"陆砚。"' },
  { type: 'narration', text: '这是他第一次没有叫"陆老师"。' },
  { type: 'narration', text: '陆砚的脚步顿了一下。然后继续走。' },
  { type: 'jump', label: 'final_scene_merge' },

  // Branch B: stays silent
  { type: 'label', name: 'shen_stays_silent' },
  { type: 'narration', text: '沈临渡坐在最后一排。他没有说话。只是看着讲台上的陆砚。' },
  { type: 'narration', text: '下课铃响了。同学们陆续离开。沈临渡是最后一个。他走过讲台的时候，把一本笔记本放在讲台上。' },
  { type: 'narration', text: '那是他写的读书笔记——《归去来兮辞》的全文翻译和读后感。他第一次认真写完了所有作业。' },
  { type: 'jump', label: 'final_scene_merge' },

  // ============ 尾声：渡 ============
  { type: 'label', name: 'final_scene_merge' },
  { type: 'transition', effect: 'fade' },
  { type: 'bg', value: 'campus' },
  { type: 'char_hide_all' },
  { type: 'narration', text: '尾声 渡' },
  { type: 'narration', text: '很多年以后，沈临渡考上了大学。一所著名的重点大学，全省前百分之五。' },
  { type: 'narration', text: '裴听去了北京，偶尔给他写信。信很短，开头总是"最近怎么样"。裴苑去了法国留学，据说读完商科回去接手了家族生意。' },
  { type: 'narration', text: '母亲转到了一家省级医院，用上了医保目录里的新药。继父没再出现。裴海生被举报涉嫌非法经营——有人匿名给市场监管局写了一封信，附上了证据。' },
  { type: 'narration', text: '没有人知道那封举报信是谁写的。' },
  { type: 'narration', text: '但沈临渡心里有一个猜测。从来不敢去验证。' },

  // ============ FINAL CHOICE ============
  { type: 'choice', choices: [
    { text: '去支教点找陆砚', jump: 'ending_find_lu', flag: 'final_choice', value: 'find' },
    { text: '远远地祝福，不打扰他的生活', jump: 'ending_let_go', flag: 'final_choice', value: 'letgo' }
  ] },

  // ============ TRUE ENDING: 渡 ============
  { type: 'label', name: 'ending_find_lu' },
  { type: 'transition', effect: 'fade' },
  { type: 'bg', value: 'campus' },
  { type: 'narration', text: '沈临渡坐了一天一夜的火车，到了陆砚支教的那个偏远小镇。' },
  { type: 'narration', text: '他在镇上的小学门口站了很久。下课铃响了，一群孩子从教室里涌出来。最后走出来的是陆砚。' },
  { type: 'narration', text: '他瘦了一些。白衬衫还是一尘不染。' },
  { type: 'narration', text: '陆砚看到他的时候，整个人停住了。' },
  { type: 'dialogue', speaker: '沈临渡', text: '"陆老师。"' },
  { type: 'narration', text: '他笑了。一个干净的、不问前因后果的笑。' },
  { type: 'dialogue', speaker: '沈临渡', text: '"我的世界——不止一种颜色了。"' },
  { type: 'narration', text: '陆砚看了他很久。很久很久。' },
  { type: 'narration', text: '然后他也笑了。' },
  { type: 'narration', text: '远处是山，天空很蓝。沈临渡穿了一件干净的白色T恤，人高了很多。他向陆砚比了一个"V"字。' },
  { type: 'narration', text: '像是渡过了一条很长很长的河流。' },
  { type: 'ending', ending: 'true' },

  // ============ ALTERNATE ENDING: 光 ============
  { type: 'label', name: 'ending_let_go' },
  { type: 'transition', effect: 'fade' },
  { type: 'bg', value: 'campus' },
  { type: 'narration', text: '沈临渡把那封写好的信折好，放进抽屉里。' },
  { type: 'narration', text: '信上只有一句话："陆老师，我考上大学了。"' },
  { type: 'narration', text: '他没有寄。' },
  { type: 'narration', text: '他知道那个人的选择——那个人选择退到最安全的距离。不是因为不爱，是因为太爱了。' },
  { type: 'narration', text: '如果陆砚选择当一道光，那他就让那道光照亮自己。然后把光分给别人。' },
  { type: 'narration', text: '沈临渡后来做了很多事。大学毕业后，他资助了一个贫困生。每个月寄一点钱。不多，但是够那个孩子吃上一日三餐。' },
  { type: 'narration', text: '他在汇款单的备注栏里写："这个世界不止一种颜色。加油。不要放弃。"' },
  { type: 'narration', text: '他没有署名。' },
  { type: 'ending', ending: 'good' },

  // ============ BAD ENDING marker (reached if player fails key choices) ============
  { type: 'label', name: 'bad_ending_fallback' },
  { type: 'ending', ending: 'bad' }
];

// Export
window.STORY_SCRIPT = STORY_SCRIPT;
